language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"


install:
  - pip install -r requirements.txt
  - pip install .
  - pip install -r requirements-test.txt --upgrade
# command to run tests
script:
  - py.test -s tests/
  - flake8 pegparsing/ --ignore=E501