language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"


install:
  - pip install -r requirements.txt
  - pip install .
  - pip install -r requirements-test.txt --upgrade
# reph plugin, eventually will be in its own module.
  - cd pytest-reph; python setup.py install  ; cd -
script:
  - py.test -s tests/
  - flake8 pegparsing/ --ignore=E501